export const RAZORPAY_API_KEY = process.env.NEXT_PUBLIC_RAZORPAY_API_KEY;
export const RAZORPAY_APT_SECRET = process.env.NEXT_PUBLIC_RAZORPAY_APT_SECRET;
export const MONGO_URI = process.env.NEXT_PUBLIC_MONGO_URI;
